// <auto-generated />
using System;
using Abn.Analytics.Data.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Abn.Analytics.Data.Migrations
{
    [DbContext(typeof(CalculatorDbContext))]
    [Migration("20210914131533_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Abn.Analytics.Domain.StatusObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StatusObject_Id");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusObject_Email");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusObject_Name");

                    b.Property<int>("Progress")
                        .HasColumnType("int")
                        .HasColumnName("StatusObject_Progress");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusObject_Result");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("StatusObject_Status");

                    b.HasKey("Id");

                    b.ToTable("StatusObject");
                });
#pragma warning restore 612, 618
        }
    }
}
