version: "3.9"
services:
  rabbit:
     image: ${DOCKER_REGISTRY-}abnrabbit
     hostname: ${RABBIT_HOST}
     restart: "always"
     healthcheck:
       test: rabbitmq-diagnostics -q ping
       interval: 30s
       timeout: 30s
       retries: 3
     ports:
       - "15672:15672"
       - "5672:5672"
     build:
       context: .
       dockerfile: ./rabbitmq/DockerFile
     env_file: .env
  SqlExpress:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlexpress
    ports:
      - "1433:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=123@hell456789DELTA

  Abn.Api:
      image: ${DOCKER_REGISTRY-}api
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - RabbitMq__HostName=${RABBIT_HOST}
        - ConnectionStrings__db=Server=sqlexpress;User Id=sa;Password=123@hell456789DELTA;
      ports:
        - "5001:5001"
        - "5000:5000"
      volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
     
      build:
        context: './'
        dockerfile: API/02.Services/AbnAnalytics/Abn.Analytics.Endpoint/Dockerfile
      depends_on:
        - SqlExpress
        - rabbit
  Abn.UI:
          image: ${DOCKER_REGISTRY-}ui
          ports:
            - "3000:3000"
          env_file: .env
          build:
            context: './UI'
            dockerfile: ./Dockerfile